### ISSUE TITLE
Inquire About Shape Mismatch in Paper

### ISSUE THREAD

**Issue by SKDDJ** [fredzzhang/atlas#33]
Hi @fredzzhang @PaulAlbert31 ,

I've been closely following your paper and I encountered a potential issue regarding matrix multiplication in one part of your work. Specifically, I noticed that the dimensions of the matrices involved do not seem to align properly for multiplication. Here's the part of the paper that I'm referring to:

![Paper Section](https://github.com/fredzzhang/atlas/assets/64692063/75199d3c-aa01-4518-96fd-7c0ad11ee605)

Upon examining the matrix dimensions, it appears that these two matrices cannot be multiplied due to their shape mismatch. To be precise, the number of columns in the first matrix must match the number of rows in the second matrix for matrix multiplication to be valid. However, in this case, they do not seem to align.

Could you please confirm if there is an error in the formation of these matrices, or if I have misunderstood something? Any clarification on this matter would be greatly appreciated.

Thank you for your attention to this issue.

Best regards,

Yiming Shi

**Comment by fredzzhang** [comment]
Hi @SKDDJ,

Thanks for taking an interest in our work.

As noted in the text (second line), we use round brackets to denote column vector concatenation. Therefore, $\boldsymbol{\tau}$ is not a row vector but a column vector. In addition, its dimension is not necessarily $m$, because each parameter block $\boldsymbol{\tau}^{(j)}$ is in fact a column vector as well.

Hope that answers your question.

Cheers,
Fred.

**Comment by SKDDJ** [comment]
Hey @fredzzhang ,

I got it. Appreciate the clarity!

Cheers,
Yiming Shi
