### ISSUE TITLE
[ Question: ATLAS Paper ]

### ISSUE THREAD

**Issue by IemProg** [fredzzhang/atlas#35]
Hi @fredzzhang @PaulAlbert31 @crodriguezo ,

Thank you for sharing the code.

I have a question about your proposed approach for learning the parameters Λ. From what I understand, for each given dataset (e.g., CIFAR-100 and SVHN), you would first need to have task vectors corresponding to each dataset, which implies that the model has already been fine-tuned on them. Then, in a second phase, you would train on CIFAR-100 to learn Λ_{CIFAR}, followed by training on SVHN to learn Λ_{SVHN}, ultimately finding a model that performs well on both datasets.

Is my understanding correct? This seems to be a two-phase training process, right?

Thanks for your help.

**Comment by fredzzhang** [comment]
Hi @IemProg,

Thanks for taking an interest in our work.

To obtain the task vectors in the first place, there is indeed fine-tuning involved. However, it does not mean that you have to go through the two-phase training process. The idea of `aTLAS` as a knowledge composition method is premised on a significant knowledge bank, with task vectors being the knowledge carrier. Therefore, when there is a new task/dataset, you can use those existing task vectors to transfer the knowledge onto the new task. As initial efforts, we will be releasing the task vectors from 22 datasets investigated in the paper. Hopefully this bank of task vectors will be expanded in the future with the help of the community.

In terms of the model merging application you were alluding to, again we assume there are already a few models with different capabilities available and we intend to produce one model that retains all capabilities. In this case, we use a small amount of data, i.e., validation sets in the experiments, to learn these coefficients, because the training data for foundation models may be, and often is, unavailable. However, if you do have access to the training data and want to produce a model that performs well on two datasets, you may as well just merge the two datasets into one and train one model directly, which will most likely result in higher performance. In the case of model merging, we are dealing with existing models. Therefore, we fine-tune these models first to emulate this scenario.

Hope that answers your question.

Cheers,
Fred.
